
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// COURSE
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const FINDBYCNAME_COURSE_SUCCESS = "FINDBYCNAME_COURSE_SUCCESS";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const LIST_COURSE_SUCCESS = "LIST_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

// MODULE
export const CREATE_MODULE_SUCCESS = "CREATE_MODULE_SUCCESS";
export const DELETE_MODULE_SUCCESS = "DELETE_MODULE_SUCCESS";
export const FINDBYMDESCRIPTION_MODULE_SUCCESS = "FINDBYMDESCRIPTION_MODULE_SUCCESS";
export const GET_MODULE_SUCCESS = "GET_MODULE_SUCCESS";
export const LIST_MODULE_SUCCESS = "LIST_MODULE_SUCCESS";
export const UPDATE_MODULE_SUCCESS = "UPDATE_MODULE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
